Controllers/InvoiceController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using RetailApp.DAL;
using RetailApp.Models;
using RetailApp.Misc;

namespace RetailApp.Controllers
{
    [Authorize]
    public class InvoiceController : Controller
    {
        private Logger logger = new Logger();
        private RetailAppContext db = new RetailAppContext();

        // GET: Invoice
        public ActionResult Zakljuci()
        {
            var racun = new Invoice();

            var stavke = db.InvoiceLines.Where(stavka => stavka.InvoiceID == null).ToList();
            foreach (var item in stavke)
            {
                item.InvoiceID = racun.InvoiceID;
                racun.UkupnoZaPlatiti += item.Ukupno;
                db.Entry(item).State = EntityState.Modified;
            }

            racun.Fiskaliziraj();
            db.Invoices.Add(racun);

            db.SaveChanges();
            try
            {
                logger.Loggs.InsertOne(new Loog { type = "info",
                    Message = "Created Invoice: " + racun.InvoiceID +
                    " JIR:" + racun.JIRRacuna +
                    " Total:" + racun.UkupnoZaPlatiti +
                    " Time:" + racun.Vrijeme
                    , dateTime = DateTime.UtcNow.ToString() });
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
            }

            return RedirectToAction("Details", new
            {
                id = racun.InvoiceID
            });
        }

        // GET: Invoice
        public ActionResult Index()
        {
            return View(db.Invoices.ToList());
        }

        // GET: Invoice/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Invoice racun = db.Invoices.Find(id);
            racun.InvoiceLines = db.InvoiceLines.Where(item => item.InvoiceID == id.Value).ToList();
            if (racun == null)
            {
                return HttpNotFound();
            }
            return View(racun);
        }

        // GET: Invoice/Create
        public ActionResult Create()
        {
            var racun = new Invoice { InvoiceLines = new List<InvoiceLine>() };
            return View(racun);
        }

        // POST: Invoice/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "InvoiceID,Vrijeme,UkupnoZaPlatiti")] Invoice racun)
        {
            if (ModelState.IsValid)
            {
                racun.InvoiceID = Guid.NewGuid();
                db.Invoices.Add(racun);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(racun);
        }

        // GET: Invoice/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Invoice racun = db.Invoices.Find(id);
            if (racun == null)
            {
                return HttpNotFound();
            }
            return View(racun);
        }

        // POST: Invoice/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "InvoiceID,Vrijeme,UkupnoZaPlatiti")] Invoice racun)
        {
            if (ModelState.IsValid)
            {
                db.Entry(racun).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(racun);
        }

        // GET: Invoice/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Invoice racun = db.Invoices.Find(id);
            racun.InvoiceLines = db.InvoiceLines.Where(item => item.InvoiceID == id.Value).ToList();
            if (racun == null)
            {
                return HttpNotFound();
            }
            return View(racun);
        }

        // POST: Invoice/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            Invoice racun = db.Invoices.Find(id);
            db.Invoices.Remove(racun);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/ItemController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using RetailApp.DAL;
using RetailApp.Models;

namespace RetailApp.Controllers
{
    [Authorize]
    public class ItemController : Controller
    {
        private RetailAppContext db = new RetailAppContext();

        // GET: Item
        public ActionResult Index()
        {
            var artikli = db.Items.Include(a => a.Measure);
            return View(artikli.ToList());
        }

        // GET: Item/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item artikal = db.Items.Find(id);
            if (artikal == null)
            {
                return HttpNotFound();
            }
            return View(artikal);
        }

        // GET: Item/Create
        [Authorize(Roles ="Admin,Manager")]
        public ActionResult Create()
        {
            ViewBag.MeasureID = new SelectList(db.Measures, "MeasureID", "Naziv");
            return View();
        }

        // POST: Item/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,Manager")]
        public ActionResult Create([Bind(Include = "ItemID,Naziv,Cijena,Kolicina,MeasureID")] Item artikal)
        {
            if (ModelState.IsValid)
            {
                db.Items.Add(artikal);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MeasureID = new SelectList(db.Measures, "MeasureID", "Naziv", artikal.MeasureID);
            return View(artikal);
        }

        // GET: Item/Edit/5
        [Authorize(Roles = "Admin,Manager")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item artikal = db.Items.Find(id);
            if (artikal == null)
            {
                return HttpNotFound();
            }
            ViewBag.MeasureID = new SelectList(db.Measures, "MeasureID", "Naziv", artikal.MeasureID);
            return View(artikal);
        }

        // POST: Item/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,Manager")]
        public ActionResult Edit([Bind(Include = "ItemID,Naziv,Cijena,Kolicina,MeasureID")] Item artikal)
        {
            if (ModelState.IsValid)
            {
                db.Entry(artikal).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MeasureID = new SelectList(db.Measures, "MeasureID", "Naziv", artikal.MeasureID);
            return View(artikal);
        }

        // GET: Item/Delete/5
        [Authorize(Roles = "Admin,Manager")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item artikal = db.Items.Find(id);
            if (artikal == null)
            {
                return HttpNotFound();
            }
            return View(artikal);
        }

        // POST: Item/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,Manager")]
        public ActionResult DeleteConfirmed(int id)
        {
            Item artikal = db.Items.Find(id);
            db.Items.Remove(artikal);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using RetailApp.DAL;
using RetailApp.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;

namespace RetailApp.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        private RetailAppContext db = new RetailAppContext();

        // GET: User
        public ActionResult Index()
        {
            if (User.Identity.IsAuthenticated)
            {
                var user = User.Identity;
                ViewBag.Name = user.Name;
                ViewBag.displayMenu = "No";

                if (!User.IsInRole("Admin"))
                {
                    return RedirectToAction("Index", "Home");
                }
                ViewBag.displayMenu = "Yes";                
                return View(db.Users.ToList());
            }
            else
            {
                ViewBag.Name = "Not Logged IN";
            }
            return View(db.Users.ToList());
        }
       
        // GET: User/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // GET: User/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: User/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Email,Password,UserName")] User user)
        {
            if (ModelState.IsValid)
            {                
                if (user.Password != null && user.Password != "")
                {
                    var userManager = new UserManager<User>(new UserStore<User>(db));
                    var res = userManager.Create(user, user.Password);
                    if (res.Succeeded)
                    {
                        db.SaveChanges();
                    }
                    else {
                        AddErrors(res);
                        return View(user);
                    }
                }
                else {
                    AddErrors(new IdentityResult("Passwor Fle error"));
                    return View(user);
                }
                return RedirectToAction("Index");
            }

            return View(user);
        }

        // GET: User/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: User/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Email,Password,UserName")] User user)
        {
            if (ModelState.IsValid)
            {
                if (user.Password != null && user.Password != "")
                {
                    var userManager = new UserManager<User>(new UserStore<User>(db));
                    string user_id = user.Id.ToString();
                    var usr = db.Users.Single(u => u.UserName == user.UserName);

                    var res = userManager.RemovePassword(usr.Id);
                    if (res.Succeeded)
                    {
                        res = userManager.AddPassword(usr.Id, user.Password);
                        if (!res.Succeeded)
                        {
                            AddErrors(res);
                            return View(user);
                        }
                    }
                }
                //db.Entry(user).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(user);
        }

        private void AddErrors(IdentityResult result)
        {
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError("", error);
            }
        }

        // GET: User/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: User/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            User user = db.Users.Find(id);
            db.Users.Remove(user);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

       

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Shared/_Layout.cshtml
@{
    var hrenstring = System.Threading.Thread.CurrentThread.CurrentCulture.TwoLetterISOLanguageName.ToLower() == "hr" ? "en" : "hr";
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/kendocss")

    @Scripts.Render("~/bundles/modernizr")

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/kendojs")
</head>
<body>

    @Html.Partial("_Menu")


    <div class="container body-content">
        @*<h1>@ViewBag.Title</h1>*@
        @RenderBody()
        <hr />
        <footer>
            <p class="text-center text-info">&copy; @DateTime.Now.Year - ASP.NET Application</p>
        </footer>
    </div>

    @RenderSection("scripts", required: false)

    <script>
        $(function () {
            $('#Navigation a').each(function () {
                if (this.href == window.location.href) {
                    $(this).addClass("active");
                }   
            });
        });
    </script>

    @Scripts.Render("~/bundles/globalize")
    @Html.Partial("_UICultureSetup")
</body>
</html>

Views/Shared/_Menu.cshtml
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <b> @Html.ActionLink("Home ", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" }) </b>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav" id="Navigation">
                @if (Context.User.Identity.IsAuthenticated) { 
                    <li>@Html.ActionLink("Skladište", "Index", "Item")</li>
                    <li>@Html.ActionLink("Cjenik", "Index", "Product")</li>
                    <li>@Html.ActionLink("Narudžbe", "Index", "InvoiceLine")</li>
                    <li>@Html.ActionLink("Pregled računa", "Index", "Invoice")</li>
                    if (Context.User.IsInRole("Admin"))
                    {
                        <li>@Html.ActionLink("Korisnici", "Index", "User")</li>
                        <li>@Html.ActionLink("Role", "Index", "Role")</li>
                    }
                }
            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </div>
</div>

Views/Shared/_StavkeGrid.cshtml
@model IEnumerable<RetailApp.Models.InvoiceLine>

@{
    ViewBag.Title = "Index";
}
<br>
<h2>Popis stavki računa : </h2>
<br>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.RedniBroj)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Product.Naziv)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Kolicina)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cijena)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Ukupno)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.RedniBroj)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Product.Naziv)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Kolicina)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Cijena)
        </td>
        <td>
            <span class="pull-right">
                @Html.DisplayFor(modelItem => item.Ukupno)
            </span>
        </td>
        <td>
            @Html.ActionLink("Uredi", "Edit", "InvoiceLine", new { id=item.InvoiceLineID }, null) |
            @Html.ActionLink("Detalji", "Details", "InvoiceLine", new { id=item.InvoiceLineID }, null) |
            @Html.ActionLink("Obriši", "Delete", "InvoiceLine", new { id=item.InvoiceLineID }, null)
        </td>
    </tr>
}
</table>



Views/Shared/_UICultureSetup.cshtml
@{
    var culture = System.Threading.Thread.CurrentThread.CurrentCulture;
    var cultureCode = culture.TwoLetterISOLanguageName;
    var jsDatePattern = culture.DateTimeFormat.ShortDatePattern.ToUpper();
}

<script type="text/javascript">
    $.when(
        $.get("/scripts/cldr/data/@cultureCode/numbers.json"),
        $.get("/scripts/cldr/data/likelySubtags.json"),
        $.get("/scripts/cldr/data/numberingSystems.json")
    ).then(function () {
        // Normalize $.get results, we only need the JSON, not the request statuses.
        return [].slice.apply(arguments, [0]).map(function (result) {
            return result[0];
        });
    }).then(Globalize.load).then(function () {
        var globalizeNumberParser = Globalize('@cultureCode').numberParser();

        $.validator.methods.number = function (value, element) {
            if (this.optional(element))
                return true;

            if (!isNaN(globalizeNumberParser(value)))
                return true;

            return false;
        }

        $.validator.methods.range = function (value, element, param) {
            if (this.optional(element))
                return true;

            var val = globalizeNumberParser(value);

            return val >= param[0] && val <= param[1];
        }
    });

    $(function () {
        $('.date-picker').date({
            locale: '@cultureCode',
            format: '@jsDatePattern'
        });
    });
</script>

<script type="text/javascript">
    $.validator.methods.date = function (value, element) {
        if (this.optional(element) && (value == '' || value == undefined || value == null))
            return true;

        var shortDatePattern = '@jsDatePattern';

        return moment(value, shortDatePattern).isValid();
    }
</script>