Models/InvoiceLine.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace RetailApp.Models
{
    public class InvoiceLine
    {
        [Required]
        public int InvoiceLineID { get; set; }

        [Display(Name = "Redni broj")]
        [Editable(false)]
        public int RedniBroj { get; set; }

        [Display(Name = "Šifra proizvoda")]
        public int ProductID { get; set; }

        [Display(Name = "Šifra proizvoda")]
        public virtual Product Product { get; set; }

        public Guid? InvoiceID { get; set; }

        public virtual Invoice Invoice { get; set; }
        
        [Display(Name = "Količina")]
        [Required]
        public int Kolicina { get; set; }

        [DisplayFormat(DataFormatString = "{0:c}")]
        [Required]
        public decimal Cijena { get; set; }

        [DisplayFormat(DataFormatString = "{0:c}")]
        public decimal Ukupno { get; set; }
    }
}

Controllers/InvoiceController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using RetailApp.DAL;
using RetailApp.Models;
using RetailApp.Misc;

namespace RetailApp.Controllers
{
    [Authorize]
    public class InvoiceController : Controller
    {
        private Logger logger = new Logger();
        private RetailAppContext db = new RetailAppContext();

        // GET: Invoice
        public ActionResult Zakljuci()
        {
            var racun = new Invoice();

            var stavke = db.InvoiceLines.Where(stavka => stavka.InvoiceID == null).ToList();
            foreach (var item in stavke)
            {
                item.InvoiceID = racun.InvoiceID;
                racun.UkupnoZaPlatiti += item.Ukupno;
                db.Entry(item).State = EntityState.Modified;
            }

            racun.Fiskaliziraj();
            db.Invoices.Add(racun);

            db.SaveChanges();
            try
            {
                logger.Loggs.InsertOne(new Loog { type = "info",
                    Message = "Created Invoice: " + racun.InvoiceID +
                    " JIR:" + racun.JIRRacuna +
                    " Total:" + racun.UkupnoZaPlatiti +
                    " Time:" + racun.Vrijeme
                    , dateTime = DateTime.UtcNow.ToString() });
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
            }

            return RedirectToAction("Details", new
            {
                id = racun.InvoiceID
            });
        }

        // GET: Invoice
        public ActionResult Index()
        {
            return View(db.Invoices.ToList());
        }

        // GET: Invoice/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Invoice racun = db.Invoices.Find(id);
            racun.InvoiceLines = db.InvoiceLines.Where(item => item.InvoiceID == id.Value).ToList();
            if (racun == null)
            {
                return HttpNotFound();
            }
            return View(racun);
        }

        // GET: Invoice/Create
        public ActionResult Create()
        {
            var racun = new Invoice { InvoiceLines = new List<InvoiceLine>() };
            return View(racun);
        }

        // POST: Invoice/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "InvoiceID,Vrijeme,UkupnoZaPlatiti")] Invoice racun)
        {
            if (ModelState.IsValid)
            {
                racun.InvoiceID = Guid.NewGuid();
                db.Invoices.Add(racun);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(racun);
        }

        // GET: Invoice/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Invoice racun = db.Invoices.Find(id);
            if (racun == null)
            {
                return HttpNotFound();
            }
            return View(racun);
        }

        // POST: Invoice/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "InvoiceID,Vrijeme,UkupnoZaPlatiti")] Invoice racun)
        {
            if (ModelState.IsValid)
            {
                db.Entry(racun).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(racun);
        }

        // GET: Invoice/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Invoice racun = db.Invoices.Find(id);
            racun.InvoiceLines = db.InvoiceLines.Where(item => item.InvoiceID == id.Value).ToList();
            if (racun == null)
            {
                return HttpNotFound();
            }
            return View(racun);
        }

        // POST: Invoice/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            Invoice racun = db.Invoices.Find(id);
            db.Invoices.Remove(racun);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/InvoiceLineController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using RetailApp.DAL;
using RetailApp.Models;

namespace RetailApp.Controllers
{
    [Authorize]
    public class InvoiceLineController : Controller
    {
        private RetailAppContext db = new RetailAppContext();

        // GET: Stavkas
        public ActionResult Index()
        {
            var stavke = db.InvoiceLines
                .Where(s => s.InvoiceID == null)
                .Include(s => s.Invoice)   
                .Include(s => s.Product);
            return View(stavke.ToList());
        }

        // GET: Stavkas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            InvoiceLine stavka = db.InvoiceLines.Find(id);
            if (stavka == null)
            {
                return HttpNotFound();
            }
            return View(stavka);
        }

        // GET: Stavkas/Create
        public ActionResult Create()
        {
            var model = new InvoiceLine();
            model.RedniBroj = db.InvoiceLines.Count() + 1;

            var listaProizvoda = db.Products
                .Select(proizvod => new
                {
                    ProductID = proizvod.ProductID,
                    SifraINaziv = proizvod.Sifra + " - " + proizvod.Naziv,
                    CijenaProizvoda = proizvod.Cijena
                });

            ViewBag.ProductID = new SelectList(listaProizvoda, "ProductID", "SifraINaziv");
            return View(model);
        }

        // POST: Stavkas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "InvoiceLineID,RedniBroj,ProductID,Kolicina,Cijena,Ukupno")] InvoiceLine stavka)
        {
            if (ModelState.IsValid)
            {
                stavka.RedniBroj = db.InvoiceLines.Count() + 1;
                db.InvoiceLines.Add(stavka);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ProductID = new SelectList(db.Products, "ProductID", "Naziv", stavka.ProductID);
            return View(stavka);
        }

        // GET: Stavkas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            InvoiceLine stavka = db.InvoiceLines.Find(id);
            if (stavka == null)
            {
                return HttpNotFound();
            }
            ViewBag.ProductID = new SelectList(db.Products, "ProductID", "Naziv", stavka.ProductID);
            return View(stavka);
        }

        // POST: Stavkas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "InvoiceLineID,RedniBroj,ProductID,Kolicina,Cijena,Ukupno")] InvoiceLine stavka)
        {
            if (ModelState.IsValid)
            {
                db.Entry(stavka).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ProductID = new SelectList(db.Products, "ProductID", "Naziv", stavka.ProductID);
            return View(stavka);
        }

        // GET: Stavkas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            InvoiceLine stavka = db.InvoiceLines.Find(id);
            if (stavka == null)
            {
                return HttpNotFound();
            }
            return View(stavka);
        }

        // POST: Stavkas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            InvoiceLine stavka = db.InvoiceLines.Find(id);
            db.InvoiceLines.Remove(stavka);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/InvoiceLine/Create.cshtml
@model RetailApp.Models.InvoiceLine

@{
    ViewBag.Title = "Kreiranje nove stavke računa";
}

<script>
    var viewModel = {
        Products: @Html.Raw(Newtonsoft.Json.JsonConvert.SerializeObject(ViewBag.ProductID.Items))
    };
</script>

<br>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.RedniBroj, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RedniBroj, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.RedniBroj, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductID, "Šifra proizvoda", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ProductID", null, optionLabel: "", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProductID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Kolicina, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Kolicina, new { htmlAttributes = new { @class = "form-control", min = "0" } })
                @Html.ValidationMessageFor(model => model.Kolicina, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cijena, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cijena, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.Cijena, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ukupno, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ukupno, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.Ukupno, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Kreiraj" class="btn btn-danger" /> |
                <button class="btn btn-info">@Html.ActionLink("Povratak", "Index") </button>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>
        function setValue($element, value) {
            $element.val(value);
            $element.attr('value', value);
        }

        $(function () {
            $("#ProductID").kendoComboBox({
                select: function (e) {
                    var val = this.dataItem(e.item.index()).value;
                    for (i = 0; i < viewModel.Products.length; i++) {
                        if (val == viewModel.Products[i].ProductID) {
                            var c = viewModel.Products[i].CijenaProizvoda;
                            setValue($("#Cijena"), c);
                        }
                    }
                }
            });

            $('#Kolicina').on("change", function () {
                var cijenaValue = $("#Cijena").val();
                var kolicina = parseInt($('#Kolicina').val());
                if (cijenaValue != "") {
                    var cijena = parseFloat(cijenaValue);
                    setValue($("#Ukupno"), cijena * kolicina);
                }
            });
        });
    </script>
}

Views/InvoiceLine/Delete.cshtml
@model RetailApp.Models.InvoiceLine

@{
    ViewBag.Title = "Brisanje";
}

<br>
<h3><strong>Jeste li sigurni da želite izbrisati ovu stavku?</strong></h3>
<br>

<div>
    <dl class="dl-horizontal">
        <h4><dt>
            Redni broj stavke
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RedniBroj)
        </dd>

        <hr />

        <dt>
            @Html.DisplayNameFor(model => model.Product.Naziv)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Product.Naziv)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Kolicina)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Kolicina)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cijena)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cijena)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ukupno)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ukupno)
        </dd></h4>
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Izbriši" class="btn btn-danger" /> |
            <span class="btn btn-info">@Html.ActionLink("Povratak", "Index") </span> |
            <span class="btn btn-success">@Html.ActionLink("Uredi", "Edit", new { id = Model.InvoiceLineID }) </span>
        </div>
    }
</div>

Views/InvoiceLine/Details.cshtml
@model RetailApp.Models.InvoiceLine

@{
    ViewBag.Title = "Detalji";
}

<br>

<div>
    <dl class="dl-horizontal">
        <h4><dt>
            Redni broj stavke
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RedniBroj)
        </dd>

        <hr />

        <dt>
            @Html.DisplayNameFor(model => model.Product.Naziv)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Product.Naziv)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Kolicina)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Kolicina)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cijena)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cijena)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ukupno)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ukupno)
        </dd></h4>

    </dl>
</div>

<span class="btn btn-success">@Html.ActionLink("Uredi", "Edit", new { id = Model.InvoiceLineID }) </span> | 
<span class="btn btn-info">@Html.ActionLink("Povratak", "Index") </span> 

Views/InvoiceLine/Edit.cshtml
@model RetailApp.Models.InvoiceLine

@{
    ViewBag.Title = "Uredi stavku";
}

<script>
    var viewModel = {
        Products: @Html.Raw(Newtonsoft.Json.JsonConvert.SerializeObject(ViewBag.ProductID.Items))
    };
</script>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.InvoiceLineID)

        <div class="form-group">
            @Html.LabelFor(model => model.RedniBroj, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RedniBroj, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.RedniBroj, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductID, "Šifra proizvoda", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ProductID", null, optionLabel: "", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProductID, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.ProductID, "ProductID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ProductID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProductID, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.Kolicina, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Kolicina, new { htmlAttributes = new { @class = "form-control", min = "0" } })
                @Html.ValidationMessageFor(model => model.Kolicina, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cijena, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cijena, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.Cijena, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ukupno, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ukupno, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.Ukupno, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Spremi" class="btn btn-danger" /> | 
                <span class="btn btn-info">@Html.ActionLink("Povratak", "Index") </span>
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>
        function setValue($element, value) {
            $element.val(value);
            $element.attr('value', value);
        }

        $(function () {
            $("#ProductID").kendoComboBox({
                select: function (e) {
                    var val = this.dataItem(e.item.index()).value;
                    for (i = 0; i < viewModel.Products.length; i++) {
                        if (val == viewModel.Products[i].ProductID) {
                            var c = viewModel.Products[i].CijenaProizvoda;
                            setValue($("#Cijena"), c);
                        }
                    }
                }
            });

            $('#Kolicina').on("change", function () {
                var cijenaValue = $("#Cijena").val();
                var kolicina = parseInt($('#Kolicina').val());
                if (cijenaValue != "") {
                    var cijena = parseFloat(cijenaValue);
                    setValue($("#Ukupno"), cijena * kolicina);
                }
            });
        });
    </script>
}



Views/InvoiceLine/Index.cshtml
@model IEnumerable<RetailApp.Models.InvoiceLine>

@{
    ViewBag.Title = "Popis stavki";
}
<br>
<h2>Popis stavki za račun : </h2>
<br>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.RedniBroj)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Product.Naziv)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Kolicina)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cijena)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Ukupno)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.RedniBroj)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Product.Naziv)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Kolicina)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cijena)
            </td>
            <td>
                <span class="pull-right">
                    @Html.DisplayFor(modelItem => item.Ukupno)
                </span>
            </td>
            <td>
                @Html.ActionLink("Uredi", "Edit", new { id = item.InvoiceLineID }) |
                @Html.ActionLink("Detalji", "Details", new { id = item.InvoiceLineID }) |
                @Html.ActionLink("Obriši", "Delete", new { id = item.InvoiceLineID })
            </td>
        </tr>
    }

</table>
<br>
<button class="button btn btn-info LinkoviBijeli" type="button" onclick="location.href='@Url.Action("Create", "InvoiceLine")'">Kreiraj novu stavku računa</button>
<button class="button btn btn-info LinkoviBijeli" type="button" onclick="location.href='@Url.Action("Zakljuci", "Invoice")'">Zaključi račun</button>
